name: Coding-Standards

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - '!docs/**'

jobs:
  Coding-Standards:
    runs-on: ubuntu-latest
    name: "Lint code with PHPCS"
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 7.3
          extensions: mbstring, intl
          tools: composer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Install dependencies
        run: |
          composer install

      - name: Cache dependencies
        uses: actions/cache@f5ce41475b483ad7581884324a6eca9f48f8dcc7 # v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer

      - name: Run PHP CodeSniffer
        run: composer lint
