name: Package for Release

on:
  release:
    types: [ published ]

jobs:
  tag:
    name: Package new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 7.4
          extensions: mbstring, intl
          tools: composer
      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
      - name: Create Artifact
        run: |
          mkdir plugin-build
          composer archive -vvv --format=zip --file="plugin-build/wp-graphql-woocommerce"
      - name: Upload artifact
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: wp-graphql-woocommerce
          path: plugin-build/wp-graphql-woocommerce.zip
      - name: Upload release asset
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: plugin-build/wp-graphql-woocommerce.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
